In [1]:
# Import
import numpy as np

In [2]:
# Version
np.__version__

'1.20.3'

In [4]:
# Array
a = np.array([[1, 2],[3, 4]])
a

array([[1, 2],
       [3, 4]])

In [5]:
# Matrix 
b = np.matrix([[1,2],[3,4]])
b

matrix([[1, 2],
        [3, 4]])

In [6]:
# DType
q = np.array([[1, 2],[3, 4]], dtype='int8')
q

array([[1, 2],
       [3, 4]], dtype=int8)

In [7]:
# Matrix multiply
a @ b

matrix([[ 7, 10],
        [15, 22]])

In [8]:
# Matrix multiply
np.dot(a,b)

matrix([[ 7, 10],
        [15, 22]])

In [9]:
# Simple multiply equal to * operator
np.multiply(a,b)

matrix([[ 1,  4],
        [ 9, 16]])

In [10]:
# total multiply
np.prod(a)

24

In [14]:
# BroadCasting
new_array = np.array([1,2,3])
new_array + 5

array([6, 7, 8])

In [16]:
# Ones
add_array = np.ones((3,3))
add_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
# Sums
add_array = np.ones((3,3))
odd_array = np.array([5,6,7])
add_array + odd_array

array([[6., 7., 8.],
       [6., 7., 8.],
       [6., 7., 8.]])

In [18]:
# BroadCasting
a = np.ones((3,1))
b = np.array([5,6,7])
a+b

array([[6., 7., 8.],
       [6., 7., 8.],
       [6., 7., 8.]])

In [19]:
# Summation
a = np.array([[1, 2],[3, 4]])
np.sum(a)

10

In [24]:
# cumsum
S = np.cumsum(a, axis=0)
# s = np.cumsum(a, axis=1)
# s 
S

array([[1, 2],
       [4, 6]], dtype=int32)

In [26]:
# Subtract
np.subtract(a, a)

array([[0, 0],
       [0, 0]])

In [27]:
# Divition
np.divide([5,6,7], 3)

array([1.66666667, 2.        , 2.33333333])

In [28]:
# Divition
np.floor_divide([5,6,7], 3)

array([1, 2, 2], dtype=int32)

In [ ]:
# Other Operators
np.divide([5,6,7], 3)